name: 自动
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - scripts/**
      - .github/**
jobs:
  build:
    name: 运行脚本
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 设置 node 版本
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - name: 创建模板
        run: |
          npx create-docusaurus@latest website classic --package-manager yarn

      - name: 配置当前目录环境
        run: |
          yarn install

      - name: 运行脚本
        run: |
          node scripts/main.js

      - name: 构建
        run: |
          cd website
          yarn build

      - name: 发布
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
